name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - name: Run Tests
        run: bun run test:ci
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests
          fail_ci_if_error: true
          verbose: true
